Pokémons/Controllers/EntrenadorController.cs
using Pokémons.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pokémons.Controllers
{
    public class EntrenadorController : Controller
    {
        PokemonsEntities2 cnx;

        public EntrenadorController()
        {
            cnx = new PokemonsEntities2();
        }
        // GET: Entrenador
        public ActionResult Index()
        {
            return View();
        }

        // GET: Entrenador/Details/5
        public ActionResult Formulario_Entrenador()
        {

            return View();
        }

        // GET: Entrenador/Create
        public ActionResult Guardar(string id_entrenador, string nombre, int edad, string pueblo, int num_medallas, string nom_medallas)
        {
            Entrenadores entrenador = new Entrenadores()
            {
                Id_Entrenador = id_entrenador,
                Nombre = nombre,
                Edad = edad,
                Pueblo = pueblo,
                Num_Medallas = num_medallas,
                Nom_Medallas = nom_medallas,
            };
            cnx.Entrenadores.Add(entrenador);
            cnx.SaveChanges();

            return View("Detalle_Entrenador", cnx.Entrenadores.ToList());
        }

        //Listado
        public ActionResult Detalle_Entrenador()
        {
            
            return View(cnx.Entrenadores.ToList());
        }

        //Ficha
        public ActionResult Ficha_Entrenador(string id_entrenador)
        {

            return View(cnx.Entrenadores.Where(x => x.Id_Entrenador.Equals("id_entrenador")).First());
        }

        // GET: Entrenador/Edit/5
        public ActionResult Edit(string id_entrenador)
        {
            return View();
        }

        // POST: Entrenador/Edit/5
        [HttpPost]
        public ActionResult Edit(string id_entrenador, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Formulario_Entrenador");
            }
            catch
            {
                return View();
            }
        }

        // GET: Entrenador/Delete/5
        public ActionResult Delete(string id_entrenador)
        {
            return View();
        }

        // POST: Entrenador/Delete/5
        [HttpPost]
        public ActionResult Delete(string id_entrenador, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Formulario_Entrenador");
            }
            catch
            {
                return View();
            }
        }
    }
}

Pokémons/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Pokédex</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pokédex", "Formulario", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Mantenedor de Entrenador", "Formulario_Entrenador", "Entrenador")</li>
                    <li>@Html.ActionLink("Listado de Entrenadores", "Detalle_Entrenador", "Entrenador")</li>
                    <li>@Html.ActionLink("Ficha de Entrenador", "Ficha_Entrenador", "Entrenador")</li>
                    <li>@Html.ActionLink("Mantenedor de Pokémons", "Formulario", "Home")</li>
                    <li>@Html.ActionLink("Listado de Pokémons", "Listado", "Home")</li>
                    <li>@Html.ActionLink("Ficha de Pokémon", "Ficha", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Pokédex - Desarrollado por <span>Alejandro Loaiza</span></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>